// Copyright (c) 2026 Sideline Authors. All rights reserved.
// Licensed under GPL-3.0.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Lattice.Generators
{
    /// <summary>
    /// Swizzle 代码生成器
    /// 为向量类型自动生成 XX, XY, XZO 等 Swizzle 属性
    /// </summary>
    [Generator]
    public class SwizzleGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // 注册语法接收器，收集标记了 [GenerateSwizzle] 的类型
            context.RegisterForSyntaxNotifications(() => new SwizzleSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not SwizzleSyntaxReceiver receiver)
                return;

            // 获取编译信息
            var compilation = context.Compilation;
            var attributeSymbol = compilation.GetTypeByMetadataName("Lattice.Generators.GenerateSwizzleAttribute");

            if (attributeSymbol == null)
                return;

            // 为每个标记的类型生成代码
            foreach (var typeDecl in receiver.CandidateTypes)
            {
                var model = compilation.GetSemanticModel(typeDecl.SyntaxTree);
                var symbol = model.GetDeclaredSymbol(typeDecl);

                if (symbol is not INamedTypeSymbol typeSymbol)
                    continue;

                // 检查是否有 [GenerateSwizzle] 特性
                var attribute = typeSymbol.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeSymbol));

                if (attribute == null)
                    continue;

                // 获取配置
                int maxDimension = GetAttributeValue(attribute, "MaxDimension", 3);
                bool includeZero = GetAttributeValue(attribute, "IncludeZero", true);

                // 分析类型的字段/属性
                var components = GetVectorComponents(typeSymbol);
                if (components.Count == 0)
                    continue;

                // 生成代码
                var source = GenerateSwizzleCode(typeSymbol, components, maxDimension, includeZero);
                var fileName = $"{typeSymbol.Name}.Swizzle.g.cs";

                context.AddSource(fileName, source);
            }
        }

        /// <summary>
        /// 获取特性构造函数或命名参数的值
        /// </summary>
        private static T GetAttributeValue<T>(AttributeData attribute, string name, T defaultValue)
        {
            // 查找命名参数
            foreach (var namedArg in attribute.NamedArguments)
            {
                if (namedArg.Key == name && namedArg.Value.Value is T value)
                    return value;
            }

            // 查找构造函数参数（简化处理，假设顺序）
            // 这里简化处理，实际项目中可能需要更复杂的逻辑
            return defaultValue;
        }

        /// <summary>
        /// 分析向量类型的组件（X, Y, Z）
        /// </summary>
        private static List<(string name, string type)> GetVectorComponents(INamedTypeSymbol typeSymbol)
        {
            var components = new List<(string, string)>();

            // 查找只读字段或属性（X, Y, Z）
            var members = typeSymbol.GetMembers();

            // 按 X, Y, Z, W 顺序
            var componentNames = new[] { "X", "Y", "Z", "W" };

            foreach (var name in componentNames)
            {
                var member = members.FirstOrDefault(m =>
                    m.Name == name &&
                    m.DeclaredAccessibility == Accessibility.Public &&
                    (m.Kind == SymbolKind.Field || m.Kind == SymbolKind.Property));

                if (member != null)
                {
                    var type = member switch
                    {
                        IFieldSymbol f => f.Type.ToDisplayString(),
                        IPropertySymbol p => p.Type.ToDisplayString(),
                        _ => "FP"
                    };
                    components.Add((name, type));
                }
            }

            return components;
        }

        /// <summary>
        /// 生成 Swizzle 代码
        /// </summary>
        private static string GenerateSwizzleCode(
            INamedTypeSymbol typeSymbol,
            List<(string name, string type)> components,
            int maxDimension,
            bool includeZero)
        {
            var sb = new StringBuilder();
            var typeName = typeSymbol.Name;
            var namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToDisplayString();

            // 文件头
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by SwizzleGenerator");
            sb.AppendLine("// Do not modify manually");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            // 命名空间
            if (namespaceName != null)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            // 类型声明
            sb.AppendLine($"    partial struct {typeName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        #region Swizzle Properties (Generated) - {components.Count}D");
            sb.AppendLine();

            // 组件列表（可能包含 O）
            var swizzleChars = components.Select(c => c.name[0]).ToList();
            if (includeZero)
                swizzleChars.Add('O');

            // 生成 2D Swizzle (XX, XY, YX, YY, XO, OX, ...)
            GenerateSwizzleDimension(sb, typeName, components, swizzleChars, 2, "FPVector2");

            // 生成 3D Swizzle (如果需要且类型支持)
            if (maxDimension >= 3 && components.Count >= 2)
            {
                sb.AppendLine();
                GenerateSwizzleDimension(sb, typeName, components, swizzleChars, 3, "FPVector3");
            }

            // 注意：4D Swizzle 需要 FPVector4 类型存在，当前未实现
            // if (maxDimension >= 4 && components.Count >= 2)
            // {
            //     sb.AppendLine();
            //     GenerateSwizzleDimension(sb, typeName, components, swizzleChars, 4, "FPVector4");
            // }

            sb.AppendLine();
            sb.AppendLine("        #endregion");
            sb.AppendLine("    }");

            if (namespaceName != null)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// 生成指定维度的 Swizzle
        /// </summary>
        private static void GenerateSwizzleDimension(
            StringBuilder sb,
            string sourceTypeName,
            List<(string name, string type)> components,
            List<char> swizzleChars,
            int dimension,
            string returnTypeName)
        {
            sb.AppendLine($"        // {dimension}D Swizzle");

            // 笛卡尔积生成所有组合
            var combinations = GenerateCombinations(swizzleChars, dimension);

            foreach (var combo in combinations)
            {
                var swizzleName = new string(combo);
                var propertyDoc = $"/// <summary>Swizzle: ({string.Join(", ", combo.Select(c => GetComponentDoc(c, components)))})</summary>";

                // 构建返回值表达式
                var args = new List<string>();
                foreach (var c in combo)
                {
                    if (c == 'O')
                        args.Add("FP.Zero");
                    else
                        args.Add(c.ToString());
                }

                var constructorArgs = string.Join(", ", args);

                sb.AppendLine($"        {propertyDoc}");
                sb.AppendLine($"        public readonly {returnTypeName} {swizzleName} => new({constructorArgs});");
            }
        }

        /// <summary>
        /// 生成字符组合的笛卡尔积
        /// </summary>
        private static List<char[]> GenerateCombinations(List<char> chars, int length)
        {
            var result = new List<char[]>();
            GenerateCombinationsRecursive(chars, length, new char[length], 0, result);
            return result;
        }

        private static void GenerateCombinationsRecursive(List<char> chars, int length, char[] current, int position, List<char[]> result)
        {
            if (position == length)
            {
                result.Add((char[])current.Clone());
                return;
            }

            foreach (var c in chars)
            {
                current[position] = c;
                GenerateCombinationsRecursive(chars, length, current, position + 1, result);
            }
        }

        /// <summary>
        /// 获取组件的文档说明
        /// </summary>
        private static string GetComponentDoc(char c, List<(string name, string type)> components)
        {
            if (c == 'O')
                return "0";

            var comp = components.FirstOrDefault(x => x.name[0] == c);
            return comp.name ?? c.ToString();
        }
    }

    /// <summary>
    /// 语法接收器：收集可能的类型声明
    /// </summary>
    public class SwizzleSyntaxReceiver : ISyntaxReceiver
    {
        public List<StructDeclarationSyntax> CandidateTypes { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // 收集所有 struct 声明（后续会筛选有特性的）
            if (syntaxNode is StructDeclarationSyntax structDecl)
            {
                CandidateTypes.Add(structDecl);
            }
        }
    }
}
