source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end

# Windows 和 JRuby 需要
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Windows 下的性能优化
platforms :mingw, :x64_mingw, :mswin do
  gem "wdm", "~> 0.1"
end

# JRuby 需要
platforms :jruby do
  gem "http_parser.rb", "~> 0.6.0"
end
